defaults: &defaults
  
  BASIC: 0  
  NCTU_CCE: 1
  NCTU_CCE_credit: 2
  NCTU_CCE_camp: 3

  ROLE_ADMIN: 0
  ROLE_MEMBER: 1
    
    
development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults