defaults: &defaults
    
  BASIC: 0  
  NCTU_CCE: 1
  NCTU_CCE_credit: 2
  NCTU_CCE_camp: 3

  ROLE_ADMIN: 0
  ROLE_MEMBER: 1

  SOURCE_OTHERS: 0     
  SOURCE_WEBSITE: 1
  SOURCE_POSTER: 2
  SOURCE_EMAIL: 3    
  SOURCE_PROFESSOR: 4 
    
development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults